services:
  cipher-api:
    build: .
    image: cipher-api
    ports:
      - "3005:3000"
    environment:
      - CIPHER_API_PREFIX=""
    env_file:
      - .env
    command:
      [
        "sh",
        "-c",
        "node dist/src/app/index.cjs --mode api --port 3005 --host 0.0.0.0 --agent /app/memAgent/cipher.yml --mcp-transport-type sse",
      ]
    volumes:
      - ./memAgent:/app/memAgent:ro
      - cipher-data:/app/.cipher
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      - SERVICE_FQDN_QDRANT_6333
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}    
    ports:
      - "6333"
    volumes:
      - qdrant_data_cipher:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3      
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}* # <-- REQUIRED
    ports:
      - "6379"
    volumes:
      - redis_data_cipher:/data
    restart: unless-stopped

  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH} # ⚠️ change password
    ports:
      - "7474" # HTTP Web UI
      - "7687" # Bolt protocol
    volumes:
      - neo4j_data_cipher:/data
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # ⚠️ change user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # ⚠️ change password
      - POSTGRES_DB=cipherdb
    ports:
      - "5432"
    volumes:
      - postgres_data_cipher:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  cipher-data:
  qdrant_data_cipher:
  redis_data_cipher:
  neo4j_data_cipher:
  postgres_data_cipher:
